server:
  port: 8082
spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
  datasource:
    driver-class-name: org.postgresql.Driver
    #private config
    hikari:
      maximum-pool-size: 3
logging:
  level:
    ROOT: INFO